name: UI Automation Tests  

on:  
  push:  
    branches: [ "main" ]  
  pull_request:  
    branches: [ "main" ]  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    container:  
      image: cromo/google-chrome  # Usar una imagen de Docker con Chrome preinstalado  

    steps:  
    - uses: actions/checkout@v4  
    - name: Set up JDK 22  
      uses: actions/setup-java@v4  
      with:  
        java-version: '22'  
        distribution: 'temurin'  

    - name: Grant execute permission for gradlew  
      run: chmod +x gradlew  

    - name: Build with Gradle Wrapper  
      run: ./gradlew build  

    - name: Capture System.out  
      if: always()  
      run: cat system.out > system_out.log 2>&1 || true  
      shell: bash  
    - name: Print System.out  
      if: always()  
      run: cat system_out.log  
      shell: bash  

    - name: Print Chrome and Chromedriver Versions  
      run: |  
        google-chrome --version || true  
        chromedriver --version || true  

    - name: Run Tests  
      run: ./gradlew test -Dwebdriver.chrome.driver=/usr/bin/chromedriver --headless  

    - name: Capture Test Output  
      run: ./gradlew test > test_output.log 2>&1  

    - name: Print Test Output  
      run: cat test_output.log  

    - name: Run Checkstyle  
      run: ./gradlew checkstyleMain  

    - name: Upload Checkstyle report  
      uses: actions/upload-artifact@v4  
      with:  
        name: checkstyle-report  
        path: build/reports/checkstyle  

  dependency-submission:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: write  

    steps:  
    - uses: actions/checkout@v4  
    - name: Set up JDK 22 for Dependency Submission  
      uses: actions/setup-java@v4  
      with:  
        java-version: '22'  
        distribution: 'temurin'  
    - name: Generate and submit dependency graph  
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582  