name: UI Automation Tests  

on:  
  push:  
    branches: 
      - main
      - 'feature/**' 
  pull_request:  
    branches:
      - main

  schedule:  
    - cron: "0 8 * * *"  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: read  

    steps:  
    - uses: actions/checkout@v4  

    - name: Set up JDK 22  
      uses: actions/setup-java@v4  
      with:  
        java-version: '22'  
        distribution: 'temurin'  

    - name: Setup Gradle  
      uses: gradle/actions/setup-gradle@v3  

    - name: Install Chrome  
      run: |  
        sudo apt-get update  
        sudo apt-get install -y google-chrome-stable  

    - name: Debug - Print Chrome and Chromedriver Versions  
      run: |  
        google-chrome --version  
        chromedriver --version # Si está disponible en el PATH  

    - name: Build with Gradle Wrapper  
      run: ./gradlew build  

    - name: Run Checkstyle  
      run: ./gradlew checkstyleMain checkstyleTest  

    - name: Upload Checkstyle report  
      uses: actions/upload-artifact@v4  
      with:  
        name: checkstyle-report  
        path: build/reports/checkstyle  
    
    - name: Run Tests  
      run: ./gradlew test --tests "runner.Scenario1"  