# This workflow uses actions that are not certified by GitHub.  
# They are provided by a third-party and are governed by  
# separate terms of service, privacy policy, and support  
# documentation.  

name: Login Test Cases  

on:  
  push:  
    branches: [ "main" ]  
  pull_request:  
    types: [opened, synchronize, reopened]  
  schedule:  
    - cron: "0 8 * * *"  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: read  

    steps:  
    - uses: actions/checkout@v4  
    - name: Set up JDK 21  
      uses: actions/setup-java@v4  
      with:  
        java-version: '21'  
        distribution: 'temurin'  

    - name: Setup Gradle  
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582  

    - name: Build with Gradle Wrapper  
      run: ./gradlew build  

    - name: Run Cucumber Tests  
      run: ./gradlew test --tests "src/test/java/runner/*"  

    - name: Run Checkstyle  
      run: ./gradlew checkstyleMain checkstyleTest  

  dependency-submission:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: write  

    steps:  
    - uses: actions/checkout@v4  
    - name: Set up JDK 21 for Dependency Submission  
      uses: actions/setup-java@v4  
      with:  
        java-version: '21'  
        distribution: 'temurin'  
    - name: Generate and submit dependency graph  
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 