# This workflow uses actions that are not certified by GitHub.  
# They are provided by a third-party and are governed by  
# separate terms of service, privacy policy, and support  
# documentation.  

name: Login Test Cases  

on:  
  push:  
    branches: [ "main" ]  
  pull_request:  
    types: [opened, synchronize, reopened]  
  schedule:  
    - cron: "0 8 * * *"  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: read  

    steps:  
    - uses: actions/checkout@v4  

    - name: Set up JDK 22  
      uses: actions/setup-java@v4  
      with:  
        java-version: '22'  
        distribution: 'temurin'  

    - name: Cache Gradle packages  
      uses: actions/cache@v4  
      with:  
        path: |  
          ~/.gradle/caches  
          ~/.gradle/wrapper  
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}  
        restore-keys: |  
          ${{ runner.os }}-gradle-  

    - name: Setup Gradle  
      uses: gradle/actions/setup-gradle@v3  

    # Añadimos el paso para imprimir las versiones de Chrome y Chromedriver  
    - name: Debug - Print Chrome and Chromedriver Versions  
      run: |  
        google-chrome --version  
        chromedriver --version # Si está disponible en el PATH  

    # Asegurarnos de que Chrome está instalado (necesario para Selenium)  
    - name: Install Chrome  
      run: |  
        sudo apt-get update  
        sudo apt-get install -y google-chrome-stable  

    - name: Grant execute permission for gradlew  
      run: chmod +x gradlew  

    - name: Build with Gradle Wrapper  
      run: ./gradlew build  

    - name: Run Tests  
      run: ./gradlew test --tests "runner.Scenario1"  

    - name: Run Checkstyle  
      run: ./gradlew checkstyleMain checkstyleTest  

    - name: Upload Checkstyle report  
      uses: actions/upload-artifact@v4  
      with:  
        name: checkstyle-report  
        path: build/reports/checkstyle  

  dependency-submission:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: write  

    steps:  
    - uses: actions/checkout@v4  
    - name: Set up JDK 22 for Dependency Submission  
      uses: actions/setup-java@v4  
      with:  
        java-version: '22'  
        distribution: 'temurin'  
    - name: Generate and submit dependency graph  
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582  