name: UI Automation Tests  

on:  
  push:  
    branches: 
      - main
      - 'feature/**' 
  pull_request:  
    branches:
      - main

  schedule:  
    - cron: "0 8 * * *"  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: read  

    steps:  
    - uses: actions/checkout@v4  

    - name: Set up JDK 17  
      uses: actions/setup-java@v4  
      with:  
        java-version: '17'  
        distribution: 'temurin'  

    - name: Setup Gradle  
      uses: gradle/actions/setup-gradle@v3  

    - name: Install Chrome  
      run: |  
        sudo apt-get update  
        sudo apt-get install -y google-chrome-stable  

    - name: Debug - Print Chrome and Chromedriver Versions  
      run: |  
        google-chrome --version  
        chromedriver --version # Si está disponible en el PATH  

    - name: Run Tests with Gradle  
      run: ./gradlew test --info --stacktrace

    - name: Run Checkstyle  
      run: ./gradlew checkstyleMain checkstyleTest  

    - name: Upload Checkstyle report  
      uses: actions/upload-artifact@v4  
      with:  
        name: checkstyle-report  
        path: build/reports/checkstyle/  
        retention-days: 30  

    - name: Upload Test Results  
      uses: actions/upload-artifact@v4  
      with:  
        name: test-results  
        path: build/reports/tests/  
        retention-days: 30  

    - name: Upload Allure Results  
      uses: actions/upload-artifact@v4  
      with:  
        name: allure-results  
        path: build/allure-results/  
        retention-days: 30  

    - name: Generate Allure Report  
      uses: simple-elf/allure-report-action@master  
      with:  
        allure_results: build/allure-results  
        allure_history: allure-history  
        keep_reports: 20  

    - name: Deploy Allure Report to GitHub Pages  
      uses: peaceiris/actions-gh-pages@v3  
      with:  
        github_token: ${{ secrets.GITHUB_TOKEN }}  
        publish_branch: gh-pages  
        publish_dir: allure-history  